name: main

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  # Enforce the standard of g_malloc instead of malloc in the project
  enforce-g_malloc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: enforce-g_malloc
      run: "! git grep -P '(?<!g_)malloc' ':!.valgrind.suppressions' ':!.github/workflows/main.yml'"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
       sudo env DEBIAN_FRONTEND=noninteractive apt-get install -y \
            gcc \
            libdbus-1-dev \
            libnotify-dev \
            libpango1.0-dev \
            libwayland-dev \
            wayland-protocols \
            libx11-dev \
            libxinerama-dev \
            libxrandr-dev \
            libxss-dev \
            ninja-build \
            pkg-config \
            python3-pip
        pip3 install meson

    - name: Setup
      run: meson setup build

    - name: Build
      run: ninja -C build

    - name: Run tests
      run: ninja -C build test
